config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path("dashboard-test/", TemplateView.as_view(template_name="base.html")),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("mutasiku.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("statements/", include("mutasiku.statements.urls")),
    path("jenius-report/", include("mutasiku.jenius_report.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mutasiku/jenius_report/urls.py
from django.urls import path


app_name = "jenius_report"
urlpatterns = [
]

mutasiku/statements/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import crawl_statement, statement_list_view

app_name = "statements"

urlpatterns = [
    path("list/", statement_list_view, name="list"),
    path(
        "get-statements/",
        TemplateView.as_view(template_name="statements/get_statement.html"),
        name="get_statements",
    ),
    path("crawl/", crawl_statement, name="crawl"),
]

mutasiku/users/urls.py
from django.urls import path

from mutasiku.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

mutasiku/jenius_report/models.py
from django.db import models


class Report(models.Model):
    file = models.FileField(upload_to="jenius_report")
    status = models.CharField(max_length=100, null=True, blank=True)

mutasiku/statements/models.py
from django.db import models

# Create your models here.


class Bank(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Credential(models.Model):
    userid = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE)


class Statement(models.Model):
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE)
    keterangan = models.TextField()
    keluar = models.FloatField()
    masuk = models.FloatField()
    ballance = models.FloatField()
    hash_id = models.CharField(max_length=255)
    tanggal = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

mutasiku/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

mutasiku/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

mutasiku/statements/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.db.models import Sum
from scrapyd_api import ScrapydAPI
from django_filters.views import FilterView

from .models import Credential, Statement
from .filters import StatementFilterSet

# Create your views here.

scrapyd = ScrapydAPI("http://scrapyd:6800")


class StatementListView(FilterView):
    model = Statement
    ordering = "-tanggal"
    template_name = "statements/list.html"
    filterset_class = StatementFilterSet

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["extra_data"] = self.object_list.aggregate(
            total_masuk=Sum("masuk"),
            total_keluar=Sum("keluar")
        )
        context["ballance"] = Statement.objects.order_by("-tanggal").first().ballance
        return context


statement_list_view = StatementListView.as_view()


@csrf_exempt
@require_http_methods(["POST", "GET"])
def crawl_statement(request):
    if request.method == "POST":
        month_year = request.POST.get("month_year")
        if month_year:
            month, year = month_year.split("/")
        else:
            month, year = None, None

        # TODO: use current user
        bank = request.POST.get("bank_code", "ibmandiri")
        credential = Credential.objects.first()
        task = scrapyd.schedule(
            "default",
            bank,
            month=month,
            year=year,
            userid=credential.userid,
            password=credential.password,
            to_crawl="helloworld"
        )
        return JsonResponse({"task_id": task, "status": "started"})

    task_id = request.GET.get("task_id")
    if not task_id:
        return JsonResponse({"error": "missing task_id argument"})

    status = scrapyd.job_status("default", task_id)
    return JsonResponse({"status": status})

mutasiku/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

mutasiku/templates/basebak.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}My Awesome Project{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">My Awesome Project</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

mutasiku/templates/components/heading.html
      <div class="card mb-4 wow fadeIn">

        <!--Card content-->
        <div class="card-body d-sm-flex justify-content-between">

          <h4 class="mb-2 mb-sm-0 pt-1">
            <a href="https://mdbootstrap.com/docs/jquery/" target="_blank">Home Page</a>
            <span>/</span>
            <span>Dashboard</span>
          </h4>

          <form class="d-flex justify-content-center">
            <!-- Default input -->
            <input type="search" placeholder="Type your query" aria-label="Search" class="form-control">
            <button class="btn btn-primary btn-sm my-0 p" type="submit">
              <i class="fas fa-search"></i>
            </button>

          </form>

        </div>

      </div>

mutasiku/templates/components/sidebar.html
  <div class="sidebar-fixed position-fixed">

    <a class="logo-wrapper waves-effect">
      <img src="https://mdbootstrap.com/img/logo/mdb-email.png" class="img-fluid" alt="">
    </a>

    <div class="list-group list-group-flush">
      <a href="#" class="list-group-item active waves-effect">
        <i class="fas fa-chart-pie mr-3"></i>Dashboard
      </a>
      <a class="list-group-item list-group-item-action waves-effect" href="{% url 'statements:list' %}">
        <i class="fas fa-money-check mr-3"></i>Statements</a>
      <a class="list-group-item list-group-item-action waves-effect" href="{% url 'statements:get_statements' %}">
        <i class="fas fa-search-dollar mr-3"></i>Get Statements</a>
      <a href="#" class="list-group-item list-group-item-action waves-effect">
        <i class="fas fa-user mr-3"></i>Profile</a>
      <a href="#" class="list-group-item list-group-item-action waves-effect">
        <i class="fas fa-table mr-3"></i>Tables</a>
      <a href="#" class="list-group-item list-group-item-action waves-effect">
        <i class="fas fa-map mr-3"></i>Maps</a>
      <a href="#" class="list-group-item list-group-item-action waves-effect">
        <i class="fas fa-money-bill-alt mr-3"></i>Orders</a>
    </div>

  </div>

mutasiku/templates/pages/about.html
{% extends "base.html" %}

mutasiku/templates/pages/home.html
{% extends "base.html" %}

mutasiku/templates/statements/get_statement.html
{% extends "base.html" %}
{% load static %}


{% block main %}
<div id="getStatement" class="row wave fadeIn">
  <div class="col">
    <div class="card">
      <div class="card-body">

        <div class="form-group">
          <label for="input" >Month</label>
          <input type="text" v-model="month_year" id="input" class="form-control monthpicker" placeholder="MM/YYYY" style="">
        </div>

        <div class="form-group">
          <label for="select">Bank</label>
          <div>
            <select v-model="bank" class="browser-default custom-select mb-4 initialized" id="select">
              <option value="ibmandiri" disabled selected>Mandiri (OLD)</option>
            </select>
          </div>
        </div>


        <button v-on:click="getStatement" v-bind:disabled="loading" class="btn btn-outline-info btn-rounded btn-block my-4 waves-effect z-depth-0" >Get Statement <span v-show="loading"> <i class="fas fa-spinner fa-spin"></i>
        </span>
        </button>

      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/jquery.ui.monthpicker.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<script>
  $(document).ready(() => {

    var app = new Vue({
      el: "#getStatement",
      data: {
        "bank": "ibmandiri",
        "month_year": "09/2019",
        "loading": false,
        status: null,
        interval: null,
        taskId: null,
      },
      watch: {
        loading: function(newState, prevState){
          if(newState && !prevState){
            // from false to true
            this.checkCrawlStatus()
          }
        },
        status: function(newState, prefState){
          if (newState && newState.toLowerCase() === "finished"){
            clearInterval(this.interval)
            this.loading = false;
          }
        }
      },
      methods: {
        onDateChange: function(e){
          console.log(e.target.value)
        },
        checkCrawlStatus: function(){
          this.interval = setInterval(() => {
            if (this.taskId){
              var url = "{% url 'statements:crawl' %}?task_id=" + this.taskId ;
              $.get(url).done((data) => {
                this.status = data.status
              })
            }
          }, 500);
        },

        getStatement: function(){
          var url = "{% url 'statements:crawl' %}";
          var data = {
            month_year: this.month_year,
            bank_code: this.bank
          }
          this.loading = true;
          that = this;
          $.post(url, data).
            done((data) => {
              this.taskId = data.task_id
            }).
            fail((err) => {
              this.loading = false;
              clearInterval(this.interval)
            })
        }
      },
    })


  })
</script>
{% endblock %}

mutasiku/templates/statements/list.html
{% extends "base.html" %}
{% load static crispy_forms_tags humanize %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block main %}
<div class="row wow fadeIn">
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <form action="" method="get">
          {{ filter.form | crispy }}
            <div class="form-group d-flex justify-content-around">
              <button class="btn btn-default" type="button" onclick="window.location.href = '{% url 'statements:list' %}';" >Reset</button>
              <input class="btn btn-primary" type="submit" value="Search">
            </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-8">
    <div class="card mb-3">
      <div class="card-body">
        <div class="card-deck">
          <div class="card text-white bg-primary">
            <div class="card-header">Saldo</div>
            <div class="card-body">{{ ballance|intcomma }}</div>
          </div>
          <div class="card text-white bg-success">
            <div class="card-header">Total Masuk</div>
            <div class="card-body">{{ extra_data.total_masuk|intcomma }}</div>
          </div>
          <div class="card text-white bg-secondary">
            <div class="card-header">Total Keluar</div>
            <div class="card-body">{{ extra_data.total_keluar|intcomma }}</div>
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-body">

        

        <div class="table-responsive">
          <table class="table table-striped table-fixed">
            <thead>
              <tr>
                <th scope="col">Tanggal</th>
                <th scope="col">Statement</th>
                <th scope="col">Masuk</th>
                <th scope="col">Keluar</th>
                <!-- <th scope="col">Ballance</th> -->
                <th scope="col">Bank Code</th>
              </tr>
            </thead>
            <tbody>
              {% for statement in object_list %}
              <tr>
                <th scope="row">{{ statement.tanggal|date:"d-m-Y" }}</th>
                <td>{{ statement.keterangan }}</td>
                <td>{{ statement.masuk|intcomma }}</td>
                <td>{{ statement.keluar|intcomma }} </td>
                <!-- <td>{{ statement.ballance }} </td> -->
                <th scope="row">{{ statement.bank.name }}</th>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock main %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script>
  $(document).ready(function(){
    $("form").datepicker({
      inputs: $("[name^='tanggal']")
    })
  })
</script>
{% endblock %}

mutasiku/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

mutasiku/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}